import {
  Laptop,
  Briefcase,
  GraduationCap,
  Landmark,
  Plane,
  ShoppingBag,
  MoreHorizontal,
  Zap,
  Tag,
  BatteryCharging,
  Sparkles,
  TrendingUp,
  ShieldAlert,
  ShieldCheck,
  Coins,
  Scale,
  ArrowUpRight,
  DollarSign,
  CheckCircle2,
  Heart,
  BookOpen,
  Award,
  Compass,
  Camera,
  Star,
  Target,
  Smartphone,
  Watch
} from 'lucide-react'

/**
 * Centralized Category Configuration for Decision Arena
 * Defines dynamic metadata, factors, autonomous agents, examples,
 * must-have suggestions, and deal-breakers for every supported category.
 */
export const CATEGORIES_CONFIG = {
  electronics: {
    id: 'electronics',
    label: 'Electronics',
    icon: Laptop,
    iconName: 'Laptop',
    description: 'Compare gadgets, laptops, smartphones, and compute hardware.',
    placeholder: 'Example: Choose a laptop under ₹55,000 for coding and AI/ML...',
    defaultRecommendation: 'ASUS TUF Gaming A15',
    examples: [
      {
        label: 'Choose a laptop under ₹55,000',
        description: 'I have a budget of ₹55,000 and need a laptop for coding, AI/ML projects, good battery life and display.',
        budget: '55000',
        category: 'electronics',
        subcategory: 'laptop',
      },
      {
        label: 'Flagship smartphone under ₹40,000',
        description: 'Need a smartphone under ₹40,000 with flagship Sony camera, 120Hz LTPO display, and all-day battery.',
        budget: '40000',
        category: 'electronics',
        subcategory: 'smartphone',
      },
      {
        label: 'Fitness smartwatch under ₹15,000',
        description: 'Need a reliable fitness smartwatch with accurate heart rate tracking, 5+ days battery life, and AMOLED screen.',
        budget: '15000',
        category: 'electronics',
        subcategory: 'smartwatch',
      },
    ],
    factors: [
      {
        key: 'performance',
        name: 'Performance',
        desc: 'Compute throughput, CPU, GPU, speed & multitasking',
        icon: Zap,
        iconName: 'Zap',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-600',
      },
      {
        key: 'value',
        name: 'Price / Value',
        desc: 'Price-to-spec ratio, component value & budget fit',
        icon: Tag,
        iconName: 'Tag',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-500',
      },
      {
        key: 'battery',
        name: 'Battery',
        desc: 'Battery endurance, power efficiency & portability',
        icon: BatteryCharging,
        iconName: 'BatteryCharging',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
      {
        key: 'experience',
        name: 'User Experience',
        desc: 'Display quality, keyboard ergonomics, comfort & chassis build',
        icon: Sparkles,
        iconName: 'Sparkles',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
      {
        key: 'futureProof',
        name: 'Future-proofing',
        desc: 'Longevity, upgradeability & multi-year workload headroom',
        icon: TrendingUp,
        iconName: 'TrendingUp',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
    ],
    agents: [
      {
        id: 'performance',
        name: 'Performance Agent',
        specialization: 'CPU, GPU, RAM, coding & AI/ML compute capability',
        iconName: 'Zap',
        score: 92,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Benchmarking compute, RAM & compiler throughput...',
        conclusion: 'Strong choice for coding and AI/ML workloads.',
        disagreementVerdict: 'Strong match',
        disagreementDetail: 'Prioritizes raw computing power; rates this highest among all agents.',
        strengths: [
          'High compute throughput suitable for intensive development workflows',
          'Easily handles local data modeling, Docker, and multi-core compilation',
          'Exceeds minimum RAM and processor benchmarks for AI/ML prototyping',
        ],
        concerns: [
          'Dedicated GPU may increase power usage under peak sustained workloads',
        ],
        evaluated: 'CPU performance, RAM capacity, GPU capability, and thermal headroom',
      },
      {
        id: 'value',
        name: 'Value Agent',
        specialization: 'Price, features, performance per price & budget fit',
        iconName: 'Tag',
        score: 86,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Auditing price-to-feature ratio & competitive tier pricing...',
        conclusion: 'Outstanding price-to-performance ratio within the defined budget.',
        disagreementVerdict: 'Strong value',
        disagreementDetail: 'Finds pricing optimal, but notes budget compromises in chassis materials.',
        strengths: [
          'Exceptional performance per price ratio in this budget bracket',
          'Comes comfortably within the defined budget ceiling with good feature density',
          'High component value compared to competing market alternatives',
        ],
        concerns: [
          'Minor budget compromises on secondary chassis finish and port selections',
        ],
        evaluated: 'Price, features included, performance per price, and budget fit',
      },
      {
        id: 'battery',
        name: 'Battery Agent',
        specialization: 'Battery life, power efficiency & portability',
        iconName: 'BatteryCharging',
        score: 81,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Simulating battery endurance, idle draw & mobility runtime...',
        conclusion: 'Adequate mobility, but heavy AI/ML compute will require AC power.',
        disagreementVerdict: 'Moderate match',
        disagreementDetail: 'Most critical agent; flags battery drain under unthrottled GPU tasks.',
        strengths: [
          'Solid 6–8 hour battery life during general coding and web browsing',
          'Fast-charging profile recovers 60% capacity in under 45 minutes',
          'Excellent energy efficiency in low-power idle and background states',
        ],
        concerns: [
          'Heavy AI/ML execution significantly accelerates battery drain away from the wall',
        ],
        evaluated: 'Battery expectations, power efficiency, portability, and power consumption',
      },
      {
        id: 'experience',
        name: 'Experience Agent',
        specialization: 'Display, build quality, keyboard & usability',
        iconName: 'Sparkles',
        score: 90,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Assessing keyboard travel, display clarity & chassis ergonomics...',
        conclusion: 'Top-tier ergonomics and daily tactile comfort for continuous work.',
        disagreementVerdict: 'Excellent daily feel',
        disagreementDetail: 'Rates daily ergonomic comfort very high; appreciates keyboard & screen.',
        strengths: [
          'High-resolution anti-glare display minimizes eye fatigue during long sessions',
          'Ergonomic tactile keyboard with crisp key travel ideal for developers',
          'Low acoustic fan resonance under everyday productivity tasks',
        ],
        concerns: [
          'Built-in speakers and webcam are standard quality rather than studio grade',
        ],
        evaluated: 'Display clarity, tactile keyboard, acoustic noise, and chassis build',
      },
      {
        id: 'futureProof',
        name: 'Future Agent',
        specialization: 'Longevity, upgradeability & future workload headroom',
        iconName: 'TrendingUp',
        score: 86,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Projecting 3-5 year obsolescence, upgrade paths & driver support...',
        conclusion: 'Reliable multi-year longevity with moderate hardware upgrade paths.',
        disagreementVerdict: 'Good longevity',
        disagreementDetail: 'Questions non-expandable memory vs future 5-year AI model growth.',
        strengths: [
          'Modern I/O connectivity and latest Wi-Fi standards ensure protocol longevity',
          'Reliable manufacturer driver and firmware update roadmap',
          'Thermal stability preserves component lifespan across 3–4 years',
        ],
        concerns: [
          'Fixed memory configuration restricts upgrade options if ML model sizes double in 3 years',
        ],
        evaluated: 'Longevity, upgradeability, future workload, and RAM/storage expansion',
      },
    ],
    requirements: [
      'At least 16GB RAM',
      'Good battery life',
      'Dedicated GPU for AI/ML',
      'Under ₹55,000',
    ],
    dealBreakers: [
      'Poor display',
      'Thermal overheating',
      'Less than 16GB RAM',
      'No fast charging',
    ],
    subcategories: [
      {
        id: 'laptop',
        label: 'Laptop',
        icon: Laptop,
        iconName: 'Laptop',
        description: 'Laptops, MacBooks, notebooks, and mobile workstations',
        placeholder: 'Example: Choose a laptop under ₹55,000 for coding and AI/ML...',
        defaultRecommendation: 'ASUS TUF Gaming A15',
        factors: [
          {
            key: 'performance',
            name: 'Performance',
            desc: 'Compute throughput, CPU, GPU, speed & multitasking',
            icon: Zap,
            iconName: 'Zap',
            color: 'text-indigo-600',
            accent: 'accent-indigo-600',
            bg: 'bg-indigo-600',
          },
          {
            key: 'value',
            name: 'Price / Value',
            desc: 'Price-to-spec ratio, component value & budget fit',
            icon: Tag,
            iconName: 'Tag',
            color: 'text-emerald-600',
            accent: 'accent-emerald-600',
            bg: 'bg-emerald-500',
          },
          {
            key: 'battery',
            name: 'Battery',
            desc: 'Battery endurance, power efficiency & portability',
            icon: BatteryCharging,
            iconName: 'BatteryCharging',
            color: 'text-blue-600',
            accent: 'accent-blue-600',
            bg: 'bg-blue-500',
          },
          {
            key: 'experience',
            name: 'User Experience',
            desc: 'Display quality, keyboard ergonomics, comfort & chassis build',
            icon: Sparkles,
            iconName: 'Sparkles',
            color: 'text-violet-600',
            accent: 'accent-violet-600',
            bg: 'bg-violet-500',
          },
          {
            key: 'futureProof',
            name: 'Future-proofing',
            desc: 'Longevity, upgradeability & multi-year workload headroom',
            icon: TrendingUp,
            iconName: 'TrendingUp',
            color: 'text-amber-600',
            accent: 'accent-amber-600',
            bg: 'bg-amber-500',
          },
        ],
        agents: [
          {
            id: 'performance',
            name: 'Performance Agent',
            specialization: 'CPU, GPU, RAM, coding & AI/ML compute capability',
            iconName: 'Zap',
            score: 92,
            color: 'indigo',
            accentBg: 'bg-indigo-50',
            accentText: 'text-indigo-600',
            accentBorder: 'border-indigo-200',
            evaluatingText: 'Benchmarking compute, RAM & compiler throughput...',
            conclusion: 'Strong choice for coding and AI/ML workloads.',
            disagreementVerdict: 'Strong match',
            disagreementDetail: 'Prioritizes raw computing power; rates this highest among all agents.',
            strengths: [
              'High compute throughput suitable for intensive development workflows',
              'Easily handles local data modeling, Docker, and multi-core compilation',
              'Exceeds minimum RAM and processor benchmarks for AI/ML prototyping',
            ],
            concerns: [
              'Dedicated GPU may increase power usage under peak sustained workloads',
            ],
            evaluated: 'CPU performance, RAM capacity, GPU capability, and thermal headroom',
          },
          {
            id: 'value',
            name: 'Value Agent',
            specialization: 'Price, features, performance per price & budget fit',
            iconName: 'Tag',
            score: 86,
            color: 'emerald',
            accentBg: 'bg-emerald-50',
            accentText: 'text-emerald-600',
            accentBorder: 'border-emerald-200',
            evaluatingText: 'Auditing price-to-feature ratio & competitive tier pricing...',
            conclusion: 'Outstanding price-to-performance ratio within the defined budget.',
            disagreementVerdict: 'Strong value',
            disagreementDetail: 'Finds pricing optimal, but notes budget compromises in chassis materials.',
            strengths: [
              'Exceptional performance per price ratio in this budget bracket',
              'Comes comfortably within the defined budget ceiling with good feature density',
              'High component value compared to competing market alternatives',
            ],
            concerns: [
              'Minor budget compromises on secondary chassis finish and port selections',
            ],
            evaluated: 'Price, features included, performance per price, and budget fit',
          },
          {
            id: 'battery',
            name: 'Battery Agent',
            specialization: 'Battery life, power efficiency & portability',
            iconName: 'BatteryCharging',
            score: 81,
            color: 'blue',
            accentBg: 'bg-blue-50',
            accentText: 'text-blue-600',
            accentBorder: 'border-blue-200',
            evaluatingText: 'Simulating battery endurance, idle draw & mobility runtime...',
            conclusion: 'Adequate mobility, but heavy AI/ML compute will require AC power.',
            disagreementVerdict: 'Moderate match',
            disagreementDetail: 'Most critical agent; flags battery drain under unthrottled GPU tasks.',
            strengths: [
              'Solid 6–8 hour battery life during general coding and web browsing',
              'Fast-charging profile recovers 60% capacity in under 45 minutes',
              'Excellent energy efficiency in low-power idle and background states',
            ],
            concerns: [
              'Heavy AI/ML execution significantly accelerates battery drain away from the wall',
            ],
            evaluated: 'Battery expectations, power efficiency, portability, and power consumption',
          },
          {
            id: 'experience',
            name: 'Experience Agent',
            specialization: 'Display, build quality, keyboard & usability',
            iconName: 'Sparkles',
            score: 90,
            color: 'violet',
            accentBg: 'bg-violet-50',
            accentText: 'text-violet-600',
            accentBorder: 'border-violet-200',
            evaluatingText: 'Assessing keyboard travel, display clarity & chassis ergonomics...',
            conclusion: 'Top-tier ergonomics and daily tactile comfort for continuous work.',
            disagreementVerdict: 'Excellent daily feel',
            disagreementDetail: 'Rates daily ergonomic comfort very high; appreciates keyboard & screen.',
            strengths: [
              'High-resolution anti-glare display minimizes eye fatigue during long sessions',
              'Ergonomic tactile keyboard with crisp key travel ideal for developers',
              'Low acoustic fan resonance under everyday productivity tasks',
            ],
            concerns: [
              'Built-in speakers and webcam are standard quality rather than studio grade',
            ],
            evaluated: 'Display clarity, tactile keyboard, acoustic noise, and chassis build',
          },
          {
            id: 'futureProof',
            name: 'Future Agent',
            specialization: 'Longevity, upgradeability & future workload headroom',
            iconName: 'TrendingUp',
            score: 86,
            color: 'amber',
            accentBg: 'bg-amber-50',
            accentText: 'text-amber-600',
            accentBorder: 'border-amber-200',
            evaluatingText: 'Projecting 3-5 year obsolescence, upgrade paths & driver support...',
            conclusion: 'Reliable multi-year longevity with moderate hardware upgrade paths.',
            disagreementVerdict: 'Good longevity',
            disagreementDetail: 'Questions non-expandable memory vs future 5-year AI model growth.',
            strengths: [
              'Modern I/O connectivity and latest Wi-Fi standards ensure protocol longevity',
              'Reliable manufacturer driver and firmware update roadmap',
              'Thermal stability preserves component lifespan across 3–4 years',
            ],
            concerns: [
              'Fixed memory configuration restricts upgrade options if ML model sizes double in 3 years',
            ],
            evaluated: 'Longevity, upgradeability, future workload, and RAM/storage expansion',
          },
        ],
        requirements: [
          'At least 16GB RAM for multitasking & IDEs',
          'Good battery life (6+ hours)',
          'Dedicated GPU or M-series silicon for compute',
          'FHD (1080p) IPS/OLED anti-glare display',
        ],
        dealBreakers: [
          'Severe thermal overheating under load',
          'Poor display with low brightness (<250 nits)',
          'Non-upgradeable 8GB single-channel RAM',
          'No fast-charging capability',
        ],
      },
      {
        id: 'smartphone',
        label: 'Smartphone',
        icon: Smartphone,
        iconName: 'Smartphone',
        description: 'Smartphones, Android flagships, iPhones & camera phones',
        placeholder: 'Example: Choose a smartphone under ₹40,000 with flagship camera, 120Hz display & battery...',
        defaultRecommendation: 'OnePlus 12R (5G)',
        factors: [
          {
            key: 'camera',
            name: 'Camera & Optics',
            desc: 'Sensor size, OIS stabilization, low-light imaging & 4K video',
            icon: Camera,
            iconName: 'Camera',
            color: 'text-rose-600',
            accent: 'accent-rose-600',
            bg: 'bg-rose-500',
          },
          {
            key: 'battery',
            name: 'Battery & Charging',
            desc: 'Screen-on time endurance, fast charging wattage & standby efficiency',
            icon: BatteryCharging,
            iconName: 'BatteryCharging',
            color: 'text-blue-600',
            accent: 'accent-blue-600',
            bg: 'bg-blue-500',
          },
          {
            key: 'performance',
            name: 'Performance & Gaming',
            desc: 'SoC chipset, RAM multitasking & thermal cooling headroom',
            icon: Zap,
            iconName: 'Zap',
            color: 'text-indigo-600',
            accent: 'accent-indigo-600',
            bg: 'bg-indigo-600',
          },
          {
            key: 'display',
            name: 'Display & UX',
            desc: 'AMOLED clarity, 120Hz LTPO refresh rate & outdoor sunlight nits',
            icon: Sparkles,
            iconName: 'Sparkles',
            color: 'text-violet-600',
            accent: 'accent-violet-600',
            bg: 'bg-violet-500',
          },
          {
            key: 'value',
            name: 'Price / Value',
            desc: 'Flagship-to-price ratio, software update longevity & warranty',
            icon: Tag,
            iconName: 'Tag',
            color: 'text-emerald-600',
            accent: 'accent-emerald-600',
            bg: 'bg-emerald-500',
          },
        ],
        agents: [
          {
            id: 'camera',
            name: 'Camera Agent',
            specialization: 'Optics, sensor size, low-light image processing & video stabilization',
            iconName: 'Camera',
            score: 91,
            color: 'rose',
            accentBg: 'bg-rose-50',
            accentText: 'text-rose-600',
            accentBorder: 'border-rose-200',
            evaluatingText: 'Auditing sensor size, OIS, dynamic range & low-light optics...',
            conclusion: 'Superb flagship-grade camera system for photography and content creation.',
            disagreementVerdict: 'Flagship optics',
            disagreementDetail: 'Rates optics exceptionally high; primary sensor captures top-tier stills.',
            strengths: [
              '50MP Sony main sensor with OIS produces razor-sharp low-light stills',
              'Natural color reproduction and high dynamic range in outdoor daylight',
              '4K 60fps video capture with smooth gyro-EIS stabilization',
            ],
            concerns: [
              'Ultra-wide secondary lens has softer edge sharpness in dim lighting',
            ],
            evaluated: 'Main sensor size, OIS stabilization, low-light imaging, and dynamic range',
          },
          {
            id: 'battery',
            name: 'Battery Agent',
            specialization: 'Screen-on time, fast charging & standby efficiency',
            iconName: 'BatteryCharging',
            score: 87,
            color: 'blue',
            accentBg: 'bg-blue-50',
            accentText: 'text-blue-600',
            accentBorder: 'border-blue-200',
            evaluatingText: 'Benchmarking battery endurance, charging watts & standby drain...',
            conclusion: 'All-day endurance with class-leading fast recharge speeds.',
            disagreementVerdict: 'Solid endurance',
            disagreementDetail: 'High battery capacity ensures 7.5+ hours SOT without anxiety.',
            strengths: [
              '5,500mAh cell easily delivers 7.5+ hours of active screen-on time',
              '100W fast charging achieves 0 to 100% in under 28 minutes',
              'Intelligent power management minimizes background standby drain',
            ],
            concerns: [
              'Lack of wireless charging support in this specific trim',
            ],
            evaluated: 'Screen-on time, recharge speed, standby efficiency, and cell health',
          },
          {
            id: 'performance',
            name: 'Performance Agent',
            specialization: 'SoC compute power, thermal dissipation & RAM management',
            iconName: 'Zap',
            score: 93,
            color: 'indigo',
            accentBg: 'bg-indigo-50',
            accentText: 'text-indigo-600',
            accentBorder: 'border-indigo-200',
            evaluatingText: 'Testing processor benchmarks, frame rates & thermal vapor chamber...',
            conclusion: 'Blazing fast performance with top-tier thermal dissipation.',
            disagreementVerdict: 'Peak compute',
            disagreementDetail: 'Rates SoC performance highest among all evaluation criteria.',
            strengths: [
              'Snapdragon 8 Gen 2 chipset provides blazing app launches and multitasking',
              'Vapor chamber cooling ensures sustained 60fps frame rates in gaming',
              '16GB LPDDR5X RAM keeps 15+ apps resident in memory without reload',
            ],
            concerns: [
              'Peak sustained compute throttles slightly during prolonged 4K export',
            ],
            evaluated: 'SoC compute power, vapor chamber cooling, RAM speed, and app launch latency',
          },
          {
            id: 'display',
            name: 'Display & UX Agent',
            specialization: 'AMOLED clarity, refresh rate, peak nits & touch response',
            iconName: 'Sparkles',
            score: 92,
            color: 'violet',
            accentBg: 'bg-violet-50',
            accentText: 'text-violet-600',
            accentBorder: 'border-violet-200',
            evaluatingText: 'Analyzing 120Hz LTPO refresh rates, peak nits & color accuracy...',
            conclusion: 'Gorgeous LTPO display with industry-leading outdoor brightness.',
            disagreementVerdict: 'Vivid screen',
            disagreementDetail: 'LTPO panel offers ultra-smooth refresh rates and remarkable outdoor visibility.',
            strengths: [
              '1.5K 120Hz LTPO 4.0 AMOLED panel with dynamic refresh rate adaptation',
              'Peak brightness of 4,500 nits provides crystal-clear outdoor sunlight visibility',
              '2160Hz high-frequency PWM dimming eliminates eye strain in the dark',
            ],
            concerns: [
              'Curved screen edge may lead to occasional accidental palm touches',
            ],
            evaluated: 'LTPO refresh rate, peak nits brightness, color gamut, and touch sampling',
          },
          {
            id: 'value',
            name: 'Value Agent',
            specialization: 'Flagship feature density, software lifecycle & price ratio',
            iconName: 'Tag',
            score: 90,
            color: 'emerald',
            accentBg: 'bg-emerald-50',
            accentText: 'text-emerald-600',
            accentBorder: 'border-emerald-200',
            evaluatingText: 'Calculating price-to-feature value & software support tenure...',
            conclusion: 'Incredible value-for-money flagship killer in the current market.',
            disagreementVerdict: 'Optimal value',
            disagreementDetail: 'Delivers flagship specs without paying ₹80,000+ luxury premiums.',
            strengths: [
              'Flagship-level processor and camera at a sub-flagship price tier',
              'Includes 100W power adapter and protective case in the box',
              'Comprehensive 3-year OS upgrade and 4-year security patch commitment',
            ],
            concerns: [
              'No official IP68 rating, only splash-resistant IP64',
            ],
            evaluated: 'Price-to-spec ratio, in-box accessories, and software support lifecycle',
          },
        ],
        requirements: [
          '50MP OIS camera with clean low-light performance',
          'At least 5,000mAh battery with 60W+ fast charging',
          '120Hz AMOLED display with high outdoor brightness',
          'Minimum 8GB RAM + fast modern chipset',
        ],
        dealBreakers: [
          'Severe thermal throttling or stuttering under basic usage',
          'Slow charging speed (under 25W)',
          'Heavy bloatware with intrusive system ads',
          'Less than 2 years of scheduled security updates',
        ],
      },
      {
        id: 'smartwatch',
        label: 'Smartwatch',
        icon: Watch,
        iconName: 'Watch',
        description: 'Fitness smartwatches, GPS sports wearables & health trackers',
        placeholder: 'Example: Choose a fitness smartwatch under ₹15,000 with accurate HR, GPS, and 7+ days battery...',
        defaultRecommendation: 'Garmin Forerunner 165',
        factors: [
          {
            key: 'fitness',
            name: 'Fitness & Health',
            desc: 'Dual-band GPS, biometric HR sensors, HRV & workout tracking',
            icon: Heart,
            iconName: 'Heart',
            color: 'text-rose-600',
            accent: 'accent-rose-600',
            bg: 'bg-rose-500',
          },
          {
            key: 'battery',
            name: 'Battery Endurance',
            desc: 'Multi-day battery runtime, GPS tracking duration & power saving',
            icon: BatteryCharging,
            iconName: 'BatteryCharging',
            color: 'text-blue-600',
            accent: 'accent-blue-600',
            bg: 'bg-blue-500',
          },
          {
            key: 'durability',
            name: 'Durability & Build',
            desc: 'Water resistance (5 ATM), glass scratch resistance & sweat proofing',
            icon: ShieldCheck,
            iconName: 'ShieldCheck',
            color: 'text-amber-600',
            accent: 'accent-amber-600',
            bg: 'bg-amber-500',
          },
          {
            key: 'display',
            name: 'Display & UI',
            desc: 'AMOLED contrast, sunlight readability, always-on display & touch',
            icon: Sparkles,
            iconName: 'Sparkles',
            color: 'text-violet-600',
            accent: 'accent-violet-600',
            bg: 'bg-violet-500',
          },
          {
            key: 'value',
            name: 'Price / Value',
            desc: 'Metric accuracy per rupee, zero subscription fees & ecosystem value',
            icon: Tag,
            iconName: 'Tag',
            color: 'text-emerald-600',
            accent: 'accent-emerald-600',
            bg: 'bg-emerald-500',
          },
        ],
        agents: [
          {
            id: 'fitness',
            name: 'Fitness & Health Agent',
            specialization: 'Biometric HR sensors, dual-band GPS accuracy & workout analytics',
            iconName: 'Heart',
            score: 92,
            color: 'rose',
            accentBg: 'bg-rose-50',
            accentText: 'text-rose-600',
            accentBorder: 'border-rose-200',
            evaluatingText: 'Validating sensor accuracy, GPS fix speed & recovery analytics...',
            conclusion: 'Outstanding biometric and GPS tracking accuracy for athletes and runners.',
            disagreementVerdict: 'Pro-grade sensors',
            disagreementDetail: 'Excels in biometric and training metrics; benchmarked against chest straps.',
            strengths: [
              'Dual-band multi-constellation GPS locks coordinates in under 5 seconds',
              '4th-gen optical HR sensor achieves 98.5% correlation with medical chest straps',
              'Rich training metrics including HRV status, VO2 Max, and training readiness',
            ],
            concerns: [
              'ECG functionality requires regional health authority approval in some areas',
            ],
            evaluated: 'Dual-band GPS, heart-rate sensor accuracy, HRV & VO2 Max tracking',
          },
          {
            id: 'battery',
            name: 'Battery Agent',
            specialization: 'Smartwatch endurance, GPS battery life & standby runtime',
            iconName: 'BatteryCharging',
            score: 94,
            color: 'blue',
            accentBg: 'bg-blue-50',
            accentText: 'text-blue-600',
            accentBorder: 'border-blue-200',
            evaluatingText: 'Measuring multi-day standby runtime & active GPS battery life...',
            conclusion: 'Phenomenal multi-day battery endurance that eliminates daily recharge routines.',
            disagreementVerdict: 'Exceptional runtime',
            disagreementDetail: 'Rates battery endurance highest among all agents; 11-day battery life.',
            strengths: [
              'Exceptional 11-day battery life in smartwatch mode without recharging',
              'Over 19 hours of continuous GPS activity tracking on a single charge',
              'Proprietary power saving profiles ensure zero battery anxiety on trips',
            ],
            concerns: [
              'Proprietary magnetic charging puck instead of universal Qi wireless charging',
            ],
            evaluated: 'Smartwatch mode runtime, GPS tracking endurance, and standby drain',
          },
          {
            id: 'durability',
            name: 'Durability Agent',
            specialization: '5 ATM water resistance, impact durability & sweat resistance',
            iconName: 'ShieldCheck',
            score: 90,
            color: 'amber',
            accentBg: 'bg-amber-50',
            accentText: 'text-amber-600',
            accentBorder: 'border-amber-200',
            evaluatingText: 'Testing water immersion rating, bezel shock resistance & scratch proofing...',
            conclusion: 'Rugged and sweat-resistant build tailored for intense athletics.',
            disagreementVerdict: 'Athletic durability',
            disagreementDetail: '5 ATM rated casing withstands open-water swimming and rigorous workouts.',
            strengths: [
              '5 ATM water resistance rated for swimming, surfing, and open-water workouts',
              'Reinforced fiber polymer bezel and Corning Gorilla Glass 3 display crystal',
              'Tested against thermal shock and sweat corrosion under high intensity use',
            ],
            concerns: [
              'Polymer casing lacks the luxury jewelry finish of stainless steel or titanium',
            ],
            evaluated: 'Water resistance (5 ATM), impact resistance, and sweat corrosion proofing',
          },
          {
            id: 'display',
            name: 'Display & UX Agent',
            specialization: 'AMOLED legibility, outdoor nits & touch response',
            iconName: 'Sparkles',
            score: 88,
            color: 'violet',
            accentBg: 'bg-violet-50',
            accentText: 'text-violet-600',
            accentBorder: 'border-violet-200',
            evaluatingText: 'Checking outdoor sunlight nits, ambient brightness & wrist gesture wake...',
            conclusion: 'Bright, vivid AMOLED screen easily readable under direct sunlight.',
            disagreementVerdict: 'Crisp display',
            disagreementDetail: 'AMOLED panel delivers deep contrast and effortless daytime legibility.',
            strengths: [
              'Vibrant 1.2-inch AMOLED touchscreen with deep blacks and rich colors',
              'Automatic ambient brightness sensor adjusts seamlessly between direct sun and dark rooms',
              'Responsive wrist-raise wake gesture with optional Always-On Display mode',
            ],
            concerns: [
              'Always-On mode reduces total battery life from 11 days down to 5 days',
            ],
            evaluated: 'AMOLED contrast, sunlight legibility, and touch responsiveness',
          },
          {
            id: 'value',
            name: 'Value Agent',
            specialization: 'Fitness feature density, zero mandatory subscriptions & longevity',
            iconName: 'Tag',
            score: 89,
            color: 'emerald',
            accentBg: 'bg-emerald-50',
            accentText: 'text-emerald-600',
            accentBorder: 'border-emerald-200',
            evaluatingText: 'Auditing feature density & calculating subscription-free total cost of ownership...',
            conclusion: 'Best-in-class price-to-performance ratio for fitness enthusiasts.',
            disagreementVerdict: 'High value',
            disagreementDetail: 'Zero paywalled metrics gives exceptional long-term ownership value.',
            strengths: [
              'Delivers pro-tier Garmin running dynamics without the ₹50,000+ price tag',
              'Zero subscription fees for all health metrics, recovery plans, and coaching',
              'High resale value retention and durable software ecosystem support',
            ],
            concerns: [
              'No built-in speaker or mic for answering Bluetooth phone calls directly',
            ],
            evaluated: 'Feature density per rupee, zero mandatory subscription fees, and longevity',
          },
        ],
        requirements: [
          'High accuracy optical heart-rate sensor',
          'At least 5+ days battery life in smartwatch mode',
          '5 ATM water resistance (safe for swimming)',
          'Sunlight-readable AMOLED display',
        ],
        dealBreakers: [
          'Mandatory paid subscription to view basic health data',
          'Battery life under 24 hours requiring daily charging',
          'Unreliable GPS connectivity with frequent dropouts',
          'Lack of water resistance below 3 ATM',
        ],
      },
    ],
  },

  finance: {
    id: 'finance',
    label: 'Finance',
    icon: Landmark,
    iconName: 'Landmark',
    description: 'Evaluate investments, savings allocations, portfolios, and capital planning.',
    placeholder: 'Example: Which investment option is better for ₹2 lakh?',
    defaultRecommendation: 'Diversified Index & Flexi-Cap Allocation',
    examples: [
      {
        label: 'Best investment for ₹2 lakh',
        description: 'Which investment option is better for ₹2 lakh with moderate risk and long-term capital growth?',
        budget: '200000',
        category: 'finance',
      },
      {
        label: 'Emergency fund vs mutual fund',
        description: 'Deciding whether to allocate ₹1 lakh into high-yield liquid funds or broad index funds for a 3-year horizon.',
        budget: '100000',
        category: 'finance',
      },
      {
        label: 'Home loan prepay vs equity SIP',
        description: 'Comparing paying down a 8.5% interest home loan principal versus continuing a monthly equity mutual fund SIP.',
        budget: '50000',
        category: 'finance',
      },
    ],
    factors: [
      {
        key: 'returnPotential',
        name: 'Return Potential',
        desc: 'Expected annualized returns & compounding upside',
        icon: TrendingUp,
        iconName: 'TrendingUp',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-600',
      },
      {
        key: 'risk',
        name: 'Risk',
        desc: 'Downside exposure, capital preservation & volatility tolerance',
        icon: ShieldAlert,
        iconName: 'ShieldAlert',
        color: 'text-rose-600',
        accent: 'accent-rose-600',
        bg: 'bg-rose-500',
      },
      {
        key: 'liquidity',
        name: 'Liquidity',
        desc: 'Ease of withdrawal, access speed & lock-in terms',
        icon: Coins,
        iconName: 'Coins',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
      {
        key: 'stability',
        name: 'Stability',
        desc: 'Predictability, low variance & stress resilience',
        icon: Scale,
        iconName: 'Scale',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-500',
      },
      {
        key: 'growth',
        name: 'Long-term Growth',
        desc: 'Multi-year capital appreciation & inflation protection',
        icon: ArrowUpRight,
        iconName: 'ArrowUpRight',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
    ],
    agents: [
      {
        id: 'returnPotential',
        name: 'Return Agent',
        specialization: 'Yield potential, historical CAGR & alpha generation',
        iconName: 'TrendingUp',
        score: 92,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Simulating compound growth models & risk-adjusted alpha...',
        conclusion: 'High return potential with solid long-term upside.',
        disagreementVerdict: 'High upside',
        disagreementDetail: 'Rates compounding returns highest; projects solid 12-14% multi-year CAGR.',
        strengths: [
          'Strong historical risk-adjusted compounding returns across economic cycles',
          'Disciplined index tracking and minimal expense ratio drag',
          'High probability of outpacing inflation over a 5-year investment horizon',
        ],
        concerns: [
          'Requires holding patience through short-term cyclical drawdowns',
        ],
        evaluated: 'Expected yield, historical CAGR, compounding velocity, and inflation beat',
      },
      {
        id: 'risk',
        name: 'Risk Agent',
        specialization: 'Drawdown risk, capital preservation & volatility hedge',
        iconName: 'ShieldAlert',
        score: 85,
        color: 'rose',
        accentBg: 'bg-rose-50',
        accentText: 'text-rose-600',
        accentBorder: 'border-rose-200',
        evaluatingText: 'Stress-testing market volatility, drawdowns & capital risk...',
        conclusion: 'Controlled risk exposure within acceptable tolerance limits.',
        disagreementVerdict: 'Moderate risk',
        disagreementDetail: 'Cautions against short-term volatility; demands disciplined stop-losses.',
        strengths: [
          'Diversified across large-cap and resilient debt instruments',
          'Negligible single-company insolvency risk due to broad diversification',
          'Asymmetric upside profile with capped downside severity',
        ],
        concerns: [
          'Temporary market pullbacks may induce psychological holding pressure',
        ],
        evaluated: 'Downside protection, max drawdown, capital preservation, and asset beta',
      },
      {
        id: 'liquidity',
        name: 'Liquidity Agent',
        specialization: 'Cash access speed, redemption ease & exit terms',
        iconName: 'Coins',
        score: 84,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Analyzing withdrawal settlement times, lock-ins & exit loads...',
        conclusion: 'Healthy liquidity profile with easy emergency access.',
        disagreementVerdict: 'Good liquidity',
        disagreementDetail: 'Confirms quick T+1 access for debt portion while equity stays invested.',
        strengths: [
          'T+1 redemption settlement on liquid and debt portfolio sleeves',
          'No punitive multi-year lock-in restrictions or hidden penalty loads',
          'Flexible partial withdrawal capability for emergency contingencies',
        ],
        concerns: [
          'Premature equity withdrawals within 12 months trigger short-term capital gains tax',
        ],
        evaluated: 'Redemption turnaround, exit load schedule, lock-in duration, and access flexibility',
      },
      {
        id: 'stability',
        name: 'Stability Agent',
        specialization: 'Valuation predictability, low variance & stress resilience',
        iconName: 'Scale',
        score: 87,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Benchmarking credit ratings, balance sheet health & macro buffers...',
        conclusion: 'High stability and stress resistance across market cycles.',
        disagreementVerdict: 'High stability',
        disagreementDetail: 'Praises structural resilience and strong sovereign credit backing.',
        strengths: [
          'Sovereign and AAA-rated instrument backing for debt allocation',
          'Low portfolio beta dampens broader market fluctuations',
          'Consistent dividend and interest reinvestment stream',
        ],
        concerns: [
          'Slightly lower fixed yield during macro monetary easing cycles',
        ],
        evaluated: 'Portfolio variance, credit rating quality, macro resilience, and income consistency',
      },
      {
        id: 'growth',
        name: 'Growth Agent',
        specialization: 'Multi-year capital appreciation & inflation protection',
        iconName: 'ArrowUpRight',
        score: 89,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Forecasting compounding trajectory, purchasing power & 5-year outlook...',
        conclusion: 'Outstanding long-term wealth compounding engine.',
        disagreementVerdict: 'Strong growth',
        disagreementDetail: 'Enthusiastically supports multi-year compounding over passive cash deposits.',
        strengths: [
          'Exponential compound interest mechanics across a 5–10 year timeline',
          'Proactive inflation hedging through high-growth equity participation',
          'Automatic systematic reinvestment compounding untaxed inside the fund',
        ],
        concerns: [
          'Requires minimum 3–5 year commitment to unlock full compounding exponential',
        ],
        evaluated: 'Multi-year capital growth, inflation defense, reinvestment runway, and compounding power',
      },
    ],
    requirements: [
      'Moderate risk',
      'Long-term growth',
      'Easy withdrawal',
      'Low expense ratio',
    ],
    dealBreakers: [
      'Very high risk',
      'Lock-in period',
      'Unstable returns',
      'High management fees',
    ],
  },

  career: {
    id: 'career',
    label: 'Career',
    icon: Briefcase,
    iconName: 'Briefcase',
    description: 'Compare job offers, promotions, company paths, and professional transitions.',
    placeholder: 'Example: Which career path should I choose after BTech Data Science?',
    defaultRecommendation: 'Applied AI & ML Specialist Path',
    examples: [
      {
        label: 'Career after BTech Data Science',
        description: 'Which career path should I choose after BTech Data Science: Machine Learning Engineer or Product Analyst?',
        budget: '',
        category: 'career',
      },
      {
        label: 'Startup vs Big Tech offer',
        description: 'Should I join a Series A AI startup with higher equity or a Tier-1 tech firm with stable compensation?',
        budget: '',
        category: 'career',
      },
      {
        label: 'Engineering Manager vs Staff IC',
        description: 'Evaluating transitioning into people management as Engineering Manager vs continuing the Staff Individual Contributor route.',
        budget: '',
        category: 'career',
      },
    ],
    factors: [
      {
        key: 'salary',
        name: 'Salary',
        desc: 'Base compensation, bonus structure & financial upside',
        icon: DollarSign,
        iconName: 'DollarSign',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-600',
      },
      {
        key: 'skillFit',
        name: 'Skill Fit',
        desc: 'Alignment with core technical skills, passion & strengths',
        icon: CheckCircle2,
        iconName: 'CheckCircle2',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-500',
      },
      {
        key: 'growth',
        name: 'Career Growth',
        desc: 'Promotion velocity, mentorship, leadership runway & resume impact',
        icon: TrendingUp,
        iconName: 'TrendingUp',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
      {
        key: 'workLifeBalance',
        name: 'Work-Life Balance',
        desc: 'Sustainable hours, flexibility, mental health & burnout risk',
        icon: Heart,
        iconName: 'Heart',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
      {
        key: 'stability',
        name: 'Job Stability',
        desc: 'Company runway, market resilience & job security',
        icon: ShieldCheck,
        iconName: 'ShieldCheck',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
    ],
    agents: [
      {
        id: 'salary',
        name: 'Compensation Agent',
        specialization: 'Base salary, equity upside, total benefits & market benchmark',
        iconName: 'DollarSign',
        score: 88,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Auditing compensation tiers, equity value & market rate bands...',
        conclusion: 'Competitive compensation package with strong return on personal effort.',
        disagreementVerdict: 'Strong pay',
        disagreementDetail: 'Rates compensation package well above industry median for this tier.',
        strengths: [
          'Competitive base compensation package with performance-linked upside',
          'Solid comprehensive health, bonus, and retirement benefits',
          'Stock appreciation potential aligned with company trajectory',
        ],
        concerns: [
          'Equity vesting schedule requires multi-year tenure commitment',
        ],
        evaluated: 'Base salary, equity upside, performance bonus, and total rewards package',
      },
      {
        id: 'skillFit',
        name: 'Skill-Fit Agent',
        specialization: 'Technical skill alignment, responsibilities & daily ownership',
        iconName: 'CheckCircle2',
        score: 92,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Matching core technical proficiencies & daily responsibilities...',
        conclusion: 'Strong career fit with immediate application of core competencies.',
        disagreementVerdict: 'Excellent fit',
        disagreementDetail: 'Finds technical alignment near-perfect with current strengths and interests.',
        strengths: [
          'High alignment with core technical skills and engineering responsibilities',
          'Substantial daily ownership, autonomy, and direct organizational impact',
          'Direct exposure to modern production data pipelines and LLM systems',
        ],
        concerns: [
          'Steep initial learning curve for specialized domain architecture',
        ],
        evaluated: 'Technical skill alignment, role responsibilities, daily ownership, and stack modernness',
      },
      {
        id: 'growth',
        name: 'Growth Agent',
        specialization: 'Career trajectory, mentorship, promotion speed & skill durability',
        iconName: 'TrendingUp',
        score: 90,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Projecting 3-5 year promotions, executive visibility & resume prestige...',
        conclusion: 'Exceptional long-term growth trajectory with durable industry leverage.',
        disagreementVerdict: 'High growth',
        disagreementDetail: 'Emphasizes accelerated learning curves and future market value creation.',
        strengths: [
          'Positions resume at the forefront of high-growth technical paradigms',
          'Expansive professional network opening leadership and entrepreneurial opportunities',
          'Clear promotion milestones with active executive sponsorship',
        ],
        concerns: [
          'Rapidly evolving tech stack requires ongoing commitment to self-directed learning',
        ],
        evaluated: 'Promotion velocity, mentorship access, skill durability, and resume prestige',
      },
      {
        id: 'workLifeBalance',
        name: 'Work-Life Agent',
        specialization: 'Sustainable hours, flexibility, mental health & burnout prevention',
        iconName: 'Heart',
        score: 82,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Reviewing sprint intensity, on-call expectations & personal boundaries...',
        conclusion: 'Sustainable working pace with manageable workload intensity.',
        disagreementVerdict: 'Moderate pace',
        disagreementDetail: 'Reminds user that high-impact roles require strict boundary management.',
        strengths: [
          'Predictable sprint schedules supporting healthy work-life integration',
          'Proactive company policies regarding time off and mental wellness',
          'Flexible hybrid working arrangements minimizing commute strain',
        ],
        concerns: [
          'Quarterly launch milestones may require periodic overtime crunches',
        ],
        evaluated: 'Work-life balance, sprint intensity, schedule flexibility, and burnout resistance',
      },
      {
        id: 'stability',
        name: 'Stability Agent',
        specialization: 'Company runway, market resilience & job security',
        iconName: 'ShieldCheck',
        score: 85,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Auditing revenue durability, profitability runway & market defensibility...',
        conclusion: 'Solid employment security and high transferable market value.',
        disagreementVerdict: 'Good stability',
        disagreementDetail: 'Assesses financial runway as solid with resilient customer revenue.',
        strengths: [
          'High demand for specialized technical profile cushions external market downturns',
          'Defensible product market position with multi-year enterprise customer contracts',
          'Diverse client base insulating against sector-specific shocks',
        ],
        concerns: [
          'Broader industry hiring slowdowns may temper ad-hoc lateral mobility',
        ],
        evaluated: 'Company financial runway, industry demand, market defensibility, and employment safety',
      },
    ],
    requirements: [
      'Competitive compensation',
      'High learning curve',
      'Remote/hybrid flexibility',
      'Strong mentorship',
    ],
    dealBreakers: [
      'Toxic culture',
      'No promotion path',
      'Excessive unpaid overtime',
      'Unstable company runway',
    ],
  },

  education: {
    id: 'education',
    label: 'Education',
    icon: GraduationCap,
    iconName: 'GraduationCap',
    description: 'Compare universities, degrees, online certifications, and research programs.',
    placeholder: 'Example: Which university or master\'s program should I attend?',
    defaultRecommendation: 'Applied AI & Distributed Systems Track',
    examples: [
      {
        label: 'MS in US vs Germany',
        description: 'Evaluating MS in Computer Science in the US vs TU Munich in Germany considering tuition, living costs, and job prospects.',
        budget: '2500000',
        category: 'education',
      },
      {
        label: 'Bootcamp vs Self-Study',
        description: 'Deciding between an intensive 6-month AI bootcamp with placement assistance vs self-paced certified courses.',
        budget: '150000',
        category: 'education',
      },
    ],
    factors: [
      {
        key: 'academicQuality',
        name: 'Academic Quality',
        desc: 'Curriculum depth, research labs, syllabus rigor & faculty',
        icon: BookOpen,
        iconName: 'BookOpen',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-600',
      },
      {
        key: 'cost',
        name: 'Cost',
        desc: 'Tuition fees, living expenses, scholarships & educational ROI',
        icon: Tag,
        iconName: 'Tag',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-500',
      },
      {
        key: 'placements',
        name: 'Placements',
        desc: 'Campus recruitment, graduate salaries & employer network',
        icon: Award,
        iconName: 'Award',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
      {
        key: 'experience',
        name: 'Campus Experience',
        desc: 'Peer community, campus environment & collaborative culture',
        icon: Sparkles,
        iconName: 'Sparkles',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
      {
        key: 'futureOpportunity',
        name: 'Future Opportunity',
        desc: 'Degree prestige, alumni network leverage & global career mobility',
        icon: Compass,
        iconName: 'Compass',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
    ],
    agents: [
      {
        id: 'academicQuality',
        name: 'Academic Agent',
        specialization: 'Curriculum depth, faculty credentials & research facilities',
        iconName: 'BookOpen',
        score: 91,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Auditing curriculum rigor, faculty publications & lab access...',
        conclusion: 'Excellent academic rigor and high skill acquisition throughput.',
        disagreementVerdict: 'Top academic quality',
        disagreementDetail: 'Rates professor credentials and project milestones very high.',
        strengths: [
          'Rigorous syllabus with comprehensive hands-on project milestones',
          'Distinguished faculty with proven academic and industry track records',
          'Direct access to funded labs and high-performance computing clusters',
        ],
        concerns: [
          'Demanding assignment deadlines require disciplined weekly scheduling',
        ],
        evaluated: 'Curriculum depth, practical application, faculty expertise, and academic rigor',
      },
      {
        id: 'cost',
        name: 'Cost Agent',
        specialization: 'Total tuition, living costs, scholarships & return on investment',
        iconName: 'Tag',
        score: 85,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Analyzing tuition, debt amortization & expected salary premium...',
        conclusion: 'Solid educational ROI with proven graduate placement dividends.',
        disagreementVerdict: 'Solid ROI',
        disagreementDetail: 'Tuition is justified by post-graduate starting salary projections.',
        strengths: [
          'Strong placement record with favorable graduate debt-to-income metrics',
          'Full access to institution research labs and digital software licenses included',
          'Merit scholarship assistance available for top quartile applicants',
        ],
        concerns: [
          'Upfront tuition fee requires disciplined financing or repayment plan',
        ],
        evaluated: 'Tuition investment, debt burden, scholarship aid, and educational ROI',
      },
      {
        id: 'placements',
        name: 'Placement Agent',
        specialization: 'Graduate placement rate, median salary & recruitment tier',
        iconName: 'Award',
        score: 92,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Tracking campus hiring partnerships & median salary outcomes...',
        conclusion: 'Outstanding graduate placement network with top tier recruiters.',
        disagreementVerdict: 'Top recruitment',
        disagreementDetail: 'Strong historical placement records across global technology firms.',
        strengths: [
          '95%+ graduate placement rate within 3 months of completion',
          'Active campus recruitment drives by Fortune 500 engineering teams',
          'Dedicated career services offering personalized interview coaching',
        ],
        concerns: [
          'Top-tier international offers concentrated in highly competitive cohorts',
        ],
        evaluated: 'Placement percentage, median salary, employer network, and interview support',
      },
      {
        id: 'experience',
        name: 'Experience Agent',
        specialization: 'Peer community, campus environment & mentorship accessibility',
        iconName: 'Sparkles',
        score: 89,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Reviewing cohort diversity, campus life & collaborative culture...',
        conclusion: 'Vibrant learning community with excellent collaborative culture.',
        disagreementVerdict: 'Engaging culture',
        disagreementDetail: 'Praises cohort diversity and supportive peer collaboration.',
        strengths: [
          'Engaging seminar environment fostering open debate and critical thinking',
          'Accessible mentors and responsive teaching assistants during office hours',
          'Diverse international student cohort providing rich peer perspectives',
        ],
        concerns: [
          'Large cohort sizes in foundational lecture blocks limit individual airtime',
        ],
        evaluated: 'Campus atmosphere, mentor accessibility, peer community, and learning culture',
      },
      {
        id: 'futureOpportunity',
        name: 'Future Opportunity Agent',
        specialization: 'Global recognition, alumni network & long-term career leverage',
        iconName: 'Compass',
        score: 93,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Mapping alumni network density, credential prestige & international mobility...',
        conclusion: 'Timeless educational foundation providing multi-decade career leverage.',
        disagreementVerdict: 'Lasting prestige',
        disagreementDetail: 'Celebrates long-term brand equity and lifelong alumni network leverage.',
        strengths: [
          'Globally respected credential recognized by tier-one employers worldwide',
          'Lifelong alumni network granting recurring professional placement access',
          'Strong stepping stone for doctoral research or executive opportunities',
        ],
        concerns: [
          'Specialized electives will require periodic updates as tooling matures',
        ],
        evaluated: 'Credential prestige, alumni leverage, future market demand, and curriculum durability',
      },
    ],
    requirements: [
      'Accredited curriculum',
      'Strong placement track record',
      'Affordable tuition or loan aid',
      'Hands-on project work',
    ],
    dealBreakers: [
      'Low placement rate',
      'Hidden additional fees',
      'Outdated syllabus',
      'Lack of career support',
    ],
  },

  travel: {
    id: 'travel',
    label: 'Travel',
    icon: Plane,
    iconName: 'Plane',
    description: 'Compare destinations, vacation packages, transit routes, and itineraries.',
    placeholder: 'Example: Plan a 7-day vacation to Himachal or Goa under ₹30,000...',
    defaultRecommendation: 'Himachal Scenic Mountain Homestay',
    examples: [
      {
        label: 'Solo trip to Himachal vs Goa',
        description: 'Planning a 5-day solo vacation to Himachal or Goa with a total budget of ₹30,000 covering travel, stay, and food.',
        budget: '30000',
        category: 'travel',
      },
      {
        label: 'Family trip to Vietnam',
        description: 'Comparing 7-day family vacation packages to Vietnam vs Thailand prioritizing culture, safe stay, and local cuisine.',
        budget: '120000',
        category: 'travel',
      },
    ],
    factors: [
      {
        key: 'cost',
        name: 'Budget / Cost',
        desc: 'Flight tickets, lodging, daily expenses & total spend',
        icon: Tag,
        iconName: 'Tag',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-600',
      },
      {
        key: 'safety',
        name: 'Safety',
        desc: 'Regional security, emergency services & traveler reassurance',
        icon: ShieldCheck,
        iconName: 'ShieldCheck',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
      {
        key: 'experience',
        name: 'Experience',
        desc: 'Local gastronomy, scenery, hospitality & lasting memories',
        icon: Sparkles,
        iconName: 'Sparkles',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
      {
        key: 'convenience',
        name: 'Convenience',
        desc: 'Visa ease, transit logistics, travel times & accessibility',
        icon: Compass,
        iconName: 'Compass',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-500',
      },
      {
        key: 'attractions',
        name: 'Attractions',
        desc: 'Sightseeing density, scenic landmarks, culture & excursions',
        icon: Camera,
        iconName: 'Camera',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
    ],
    agents: [
      {
        id: 'cost',
        name: 'Budget Agent',
        specialization: 'Travel expenses, flight costs, stay rates & budget optimization',
        iconName: 'Tag',
        score: 86,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Calculating lodging rates, transit tickets & daily spend...',
        conclusion: 'Cost-effective itinerary maximizing memorable experiences within budget.',
        disagreementVerdict: 'Excellent budget fit',
        disagreementDetail: 'Rates daily spend efficiency very high within stated budget.',
        strengths: [
          'Excellent lodging rates secured within target expenditure bounds',
          'High experiential return per rupee spent on regional activities',
          'Ample financial cushion remaining for local food and souvenirs',
        ],
        concerns: [
          'Peak-season surcharges apply to select weekend excursions',
        ],
        evaluated: 'Lodging value, daily spend rate, activity ROI, and budget headroom',
      },
      {
        id: 'safety',
        name: 'Safety Agent',
        specialization: 'Regional safety index, healthcare access & traveler security',
        iconName: 'ShieldCheck',
        score: 89,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Checking local security ratings, medical facilities & terrain safety...',
        conclusion: 'Safe destination with reliable tourist infrastructure.',
        disagreementVerdict: 'High safety rating',
        disagreementDetail: 'Verified low crime rate and accessible emergency healthcare services.',
        strengths: [
          'High local safety index with dedicated tourist assistance centers',
          'Reliable medical dispensaries and emergency vehicle response',
          'Well-lit pedestrian areas and licensed transport operators',
        ],
        concerns: [
          'Mountain roads require cautious driving during sudden rain spells',
        ],
        evaluated: 'Safety index, healthcare accessibility, terrain safety, and local police support',
      },
      {
        id: 'experience',
        name: 'Experience Agent',
        specialization: 'Cultural immersion, cuisine, scenic vistas & comfort',
        iconName: 'Sparkles',
        score: 91,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Sampling regional culinary scene, scenic beauty & cultural charm...',
        conclusion: 'Immersive and memorable journey offering exceptional sensory comfort.',
        disagreementVerdict: 'Top experience',
        disagreementDetail: 'Gives highest marks for pristine vistas and authentic regional culture.',
        strengths: [
          'Warm hospitality with rich exposure to local gastronomy and culture',
          'Spectacular scenic vistas and curated off-the-beaten-path locations',
          'Tranquil mountain retreat atmosphere ideal for unwinding',
        ],
        concerns: [
          'Occasional spotty cellular connectivity in remote scenic valleys',
        ],
        evaluated: 'Hospitality quality, sensory immersion, scenic ambience, and comfort level',
      },
      {
        id: 'convenience',
        name: 'Convenience Agent',
        specialization: 'Transit duration, airport connectivity & routing friction',
        iconName: 'Compass',
        score: 84,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Mapping flight layovers, rail connectivity & transit logistics...',
        conclusion: 'Manageable transit logistics with direct regional connections.',
        disagreementVerdict: 'Good convenience',
        disagreementDetail: 'Direct overnight sleeper bus or train simplifies arrival.',
        strengths: [
          'Direct overnight connectivity minimizing daytime transit loss',
          'Walkable town centers with readily available local bike and cab rentals',
          'Digital UPI and card payment acceptance across most establishments',
        ],
        concerns: [
          'Final 30km ascent features winding mountain roads',
        ],
        evaluated: 'Transit efficiency, transfer count, road accessibility, and digital payment readiness',
      },
      {
        id: 'attractions',
        name: 'Attractions Agent',
        specialization: 'Historic landmarks, hiking trails & sightseeing variety',
        iconName: 'Camera',
        score: 90,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Compiling itinerary landmarks, hiking trails & scenic overlooks...',
        conclusion: 'Rich variety of cultural landmarks and breathtaking hiking trails.',
        disagreementVerdict: 'Abundant attractions',
        disagreementDetail: 'High-density sightseeing with varied outdoor activities.',
        strengths: [
          'Diverse mix of ancient temple architecture and alpine pine trails',
          'Spectacular sunrise and sunset viewpoints easily accessible on foot',
          'Vibrant local market streets and handicraft workshops',
        ],
        concerns: [
          'Certain heritage sites require advance entry reservation during peak weekends',
        ],
        evaluated: 'Landmark variety, trail condition, scenic viewpoints, and heritage depth',
      },
    ],
    requirements: [
      'Safe accommodation',
      'Direct or short transit',
      'Within budget ceiling',
      'Good food options',
    ],
    dealBreakers: [
      'Complicated visa delays',
      'High crime or safety alert',
      'Extreme bad weather season',
      'Overcrowded tourist traps',
    ],
  },

  shopping: {
    id: 'shopping',
    label: 'Shopping',
    icon: ShoppingBag,
    iconName: 'ShoppingBag',
    description: 'Compare consumer products, appliances, tools, and lifestyle purchases.',
    placeholder: 'Example: Which ergonomic chair or camera should I buy?',
    defaultRecommendation: 'Premium Ergonomic Series Model X',
    examples: [
      {
        label: 'Ergonomic chair under ₹20,000',
        description: 'Looking for a high-quality ergonomic mesh office chair under ₹20,000 with lumbar support for 8+ hour work days.',
        budget: '20000',
        category: 'shopping',
      },
      {
        label: 'Mirrorless camera for travel',
        description: 'Comparing Sony Alpha vs Fujifilm mirrorless cameras for travel photography under ₹80,000.',
        budget: '80000',
        category: 'shopping',
      },
    ],
    factors: [
      {
        key: 'price',
        name: 'Price',
        desc: 'Upfront retail cost, discounts & price competitiveness',
        icon: Tag,
        iconName: 'Tag',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-600',
      },
      {
        key: 'quality',
        name: 'Quality',
        desc: 'Material grade, build precision & finish standard',
        icon: CheckCircle2,
        iconName: 'CheckCircle2',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-500',
      },
      {
        key: 'features',
        name: 'Features',
        desc: 'Functional capabilities, specifications & versatility',
        icon: Sparkles,
        iconName: 'Sparkles',
        color: 'text-blue-600',
        accent: 'accent-blue-600',
        bg: 'bg-blue-500',
      },
      {
        key: 'reviews',
        name: 'Reviews',
        desc: 'Verified user ratings, community consensus & reputation',
        icon: Star,
        iconName: 'Star',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
      {
        key: 'durability',
        name: 'Durability',
        desc: 'Product lifespan, warranty coverage & wear resistance',
        icon: ShieldCheck,
        iconName: 'ShieldCheck',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
    ],
    agents: [
      {
        id: 'price',
        name: 'Price Agent',
        specialization: 'Competitive retail pricing, market discounts & budget fit',
        iconName: 'Tag',
        score: 87,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Analyzing historical price charts, seller discounts & deals...',
        conclusion: 'Competitive pricing positioned at the best value frontier.',
        disagreementVerdict: 'Good price',
        disagreementDetail: 'Identified lowest 60-day historical price point.',
        strengths: [
          'Comes comfortably within the defined budget ceiling',
          'Consistent pricing with zero artificial markups across retailers',
          'High feature density per rupee spent',
        ],
        concerns: [
          'Infrequent seasonal sales offers may present slight future price dips',
        ],
        evaluated: 'Retail price, discount stability, price-to-feature ratio, and budget headroom',
      },
      {
        id: 'quality',
        name: 'Quality Agent',
        specialization: 'Materials, build craftsmanship & manufacturing standards',
        iconName: 'CheckCircle2',
        score: 91,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Inspecting material stress tests, manufacturing tolerances & finish...',
        conclusion: 'Premium materials and rigorous build quality.',
        disagreementVerdict: 'Top craftsmanship',
        disagreementDetail: 'Rates chassis construction and mechanical joints very high.',
        strengths: [
          'Heavy-duty reinforced structural frame with tight tolerances',
          'Breathable Korean mesh fabric providing ergonomic resilience',
          'Smooth pneumatic adjustment mechanics certified for commercial grade',
        ],
        concerns: [
          'Initial assembly requires 20-30 minutes of careful tool setup',
        ],
        evaluated: 'Material grade, assembly precision, structural rigidity, and tactile finish',
      },
      {
        id: 'features',
        name: 'Features Agent',
        specialization: 'Ergonomic adjustability, versatility & everyday utility',
        iconName: 'Sparkles',
        score: 89,
        color: 'blue',
        accentBg: 'bg-blue-50',
        accentText: 'text-blue-600',
        accentBorder: 'border-blue-200',
        evaluatingText: 'Testing adjustment angles, lumbar ergonomics & utility...',
        conclusion: 'Rich feature set with multi-dimensional adjustability.',
        disagreementVerdict: 'Feature rich',
        disagreementDetail: 'Appreciates 3D armrests and multi-angle synchro tilt mechanism.',
        strengths: [
          'Full 3D armrest adjustability (height, depth, angle)',
          'Independent lumbar support depth and height tuning',
          'Multi-stage tilt lock supporting 90 to 135 degree postures',
        ],
        concerns: [
          'Headrest angle adjustment is slightly stiff out of the box',
        ],
        evaluated: 'Adjustability options, ergonomic mechanisms, utility, and user versatility',
      },
      {
        id: 'reviews',
        name: 'Review Agent',
        specialization: 'Verified buyer sentiment, long-term owner reviews & defects',
        iconName: 'Star',
        score: 90,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Aggregating thousands of verified buyer reviews & defect metrics...',
        conclusion: 'Strongly positive consensus across thousands of verified owners.',
        disagreementVerdict: 'High consensus',
        disagreementDetail: '4.6/5 average star rating with over 85% 5-star verified reviews.',
        strengths: [
          '4.6/5 aggregate rating across verified long-term owners',
          'Consistently praised for relieving lower back strain during long sessions',
          'Low return rate and prompt manufacturer support responses',
        ],
        concerns: [
          'Minor complaints regarding plastic caster wheel noise on tiled floors',
        ],
        evaluated: 'Aggregate rating, review authenticity, return rate, and defect reports',
      },
      {
        id: 'durability',
        name: 'Durability Agent',
        specialization: 'Component lifespan, warranty coverage & wear resistance',
        iconName: 'ShieldCheck',
        score: 88,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Evaluating wear cycles, warranty policies & component lifespan...',
        conclusion: 'Proven durability with multi-year warranty coverage.',
        disagreementVerdict: 'Durable lifespan',
        disagreementDetail: '3-year comprehensive on-site warranty guarantees multi-year peace of mind.',
        strengths: [
          'BIFMA-certified gas lift tested for 100,000 continuous cycles',
          '3-year manufacturer on-site warranty covering frame and mechanisms',
          'High-density anti-sag seat foam maintaining structure over years',
        ],
        concerns: [
          'Fabric mesh requires occasional vacuuming to prevent dust buildup',
        ],
        evaluated: 'Cycle stress certification, warranty terms, wear resistance, and spare parts availability',
      },
    ],
    requirements: [
      'High user ratings (4.5+)',
      'Manufacturer warranty',
      'Reliable build quality',
      'Good after-sales support',
    ],
    dealBreakers: [
      'Poor build materials',
      'No warranty coverage',
      'High failure rate in reviews',
      'Expensive replacement parts',
    ],
  },

  other: {
    id: 'other',
    label: 'Other',
    icon: MoreHorizontal,
    iconName: 'MoreHorizontal',
    description: 'Custom and general strategic decisions.',
    placeholder: 'Example: Describe any strategic decision or dilemma...',
    defaultRecommendation: 'Strategic Option A (High-Consensus Route)',
    examples: [
      {
        label: 'Relocate to a new city',
        description: 'Deciding whether to relocate to Bengaluru vs staying in Pune considering rent, commute, and career opportunities.',
        budget: '',
        category: 'other',
      },
      {
        label: 'Rent vs Buy residential property',
        description: 'Evaluating whether to buy a residential apartment or continue renting and investing the surplus capital.',
        budget: '',
        category: 'other',
      },
    ],
    factors: [
      {
        key: 'optionFit',
        name: 'Strategic Fit',
        desc: 'Alignment with core primary goals and values',
        icon: Target,
        iconName: 'Target',
        color: 'text-indigo-600',
        accent: 'accent-indigo-600',
        bg: 'bg-indigo-600',
      },
      {
        key: 'value',
        name: 'Cost / Value',
        desc: 'Financial implications, budget and return on investment',
        icon: Tag,
        iconName: 'Tag',
        color: 'text-emerald-600',
        accent: 'accent-emerald-600',
        bg: 'bg-emerald-500',
      },
      {
        key: 'risk',
        name: 'Risk',
        desc: 'Downside consequences, uncertainty and reversibility',
        icon: ShieldAlert,
        iconName: 'ShieldAlert',
        color: 'text-rose-600',
        accent: 'accent-rose-600',
        bg: 'bg-rose-500',
      },
      {
        key: 'experience',
        name: 'Experience',
        desc: 'Day-to-day satisfaction, lifestyle impact and happiness',
        icon: Sparkles,
        iconName: 'Sparkles',
        color: 'text-violet-600',
        accent: 'accent-violet-600',
        bg: 'bg-violet-500',
      },
      {
        key: 'longTermImpact',
        name: 'Long-term Impact',
        desc: 'Strategic trajectory, compounding results and 5-year outlook',
        icon: TrendingUp,
        iconName: 'TrendingUp',
        color: 'text-amber-600',
        accent: 'accent-amber-600',
        bg: 'bg-amber-500',
      },
    ],
    agents: [
      {
        id: 'optionFit',
        name: 'Fit Agent',
        specialization: 'Goal alignment, core values & strategic fit',
        iconName: 'Target',
        score: 90,
        color: 'indigo',
        accentBg: 'bg-indigo-50',
        accentText: 'text-indigo-600',
        accentBorder: 'border-indigo-200',
        evaluatingText: 'Assessing alignment with stated objectives & core goals...',
        conclusion: 'Strong alignment with defined long-term objectives.',
        disagreementVerdict: 'Strong fit',
        disagreementDetail: 'Confirms strategic alignment with user priorities.',
        strengths: [
          'High direct alignment with primary stated criteria and goals',
          'Enables immediate progress on the central objective',
          'Broad support across key stakeholders',
        ],
        concerns: [
          'Requires disciplined execution during the initial transition period',
        ],
        evaluated: 'Objective fit, value alignment, execution feasibility, and strategic focus',
      },
      {
        id: 'value',
        name: 'Value Agent',
        specialization: 'Resource efficiency, economic return & cost balance',
        iconName: 'Tag',
        score: 86,
        color: 'emerald',
        accentBg: 'bg-emerald-50',
        accentText: 'text-emerald-600',
        accentBorder: 'border-emerald-200',
        evaluatingText: 'Auditing capital expenditure, recurring cost & economic ROI...',
        conclusion: 'Prudent economic choice with sound value proposition.',
        disagreementVerdict: 'Favorable value',
        disagreementDetail: 'Economic benefits outweigh total capital outlay.',
        strengths: [
          'Favorable cost-to-benefit ratio relative to available alternatives',
          'Fits neatly within designated financial parameters',
          'Produces tangible return on time and capital invested',
        ],
        concerns: [
          'Ancillary add-ons may increase overall lifetime expenditure if unmonitored',
        ],
        evaluated: 'Acquisition cost, return on investment, economic efficiency, and recurring overhead',
      },
      {
        id: 'risk',
        name: 'Risk Agent',
        specialization: 'Downside exposure, worst-case mitigation & reversibility',
        iconName: 'ShieldAlert',
        score: 83,
        color: 'rose',
        accentBg: 'bg-rose-50',
        accentText: 'text-rose-600',
        accentBorder: 'border-rose-200',
        evaluatingText: 'Stress-testing tail risks, reversibility & downside buffers...',
        conclusion: 'Manageable risk profile with multiple contingency exit routes.',
        disagreementVerdict: 'Moderate risk',
        disagreementDetail: 'Encourages setting explicit decision checkpoint milestones.',
        strengths: [
          'Reversible decision paths available if initial outcomes underperform',
          'Downside risks are capped and well-understood',
          'Clear mitigation strategies identified for major failure modes',
        ],
        concerns: [
          'External macro volatility could extend expected payback duration',
        ],
        evaluated: 'Downside risk, path reversibility, tail risk exposure, and contingency readiness',
      },
      {
        id: 'experience',
        name: 'Experience Agent',
        specialization: 'Qualitative lifestyle, daily comfort & satisfaction',
        iconName: 'Sparkles',
        score: 88,
        color: 'violet',
        accentBg: 'bg-violet-50',
        accentText: 'text-violet-600',
        accentBorder: 'border-violet-200',
        evaluatingText: 'Measuring daily emotional friction, satisfaction & qualitative factors...',
        conclusion: 'Comfortable and reliable experience with low ongoing friction.',
        disagreementVerdict: 'High satisfaction',
        disagreementDetail: 'Anticipates positive day-to-day emotional and practical impact.',
        strengths: [
          'Pleasant and intuitive day-to-day interaction quality',
          'Thoughtful ergonomics reducing ongoing operational friction',
          'Enhances personal peace of mind and quality of life',
        ],
        concerns: [
          'A few minor edge cases require manual workarounds during onboarding',
        ],
        evaluated: 'Daily comfort, satisfaction, operational smoothness, and emotional well-being',
      },
      {
        id: 'longTermImpact',
        name: 'Future Impact Agent',
        specialization: 'Multi-year trajectory, durability & long-term compounding',
        iconName: 'TrendingUp',
        score: 87,
        color: 'amber',
        accentBg: 'bg-amber-50',
        accentText: 'text-amber-600',
        accentBorder: 'border-amber-200',
        evaluatingText: 'Forecasting multi-year durability, option value & 5-year outlook...',
        conclusion: 'Good long-term viability with respectable future adaptability.',
        disagreementVerdict: 'Durable impact',
        disagreementDetail: 'Protects long-term option value and builds strategic capital.',
        strengths: [
          'Sound structural durability accommodating future operational growth',
          'Low risk of near-term obsolescence under evolving standards',
          'Creates compounding option value for subsequent decisions',
        ],
        concerns: [
          'May require periodic review as external conditions shift over time',
        ],
        evaluated: 'Longevity, adaptability, future option value, and multi-year trajectory',
      },
    ],
    requirements: [
      'High alignment with goals',
      'Manageable execution risk',
      'Sustainable long-term outcome',
      'Reversible if needed',
    ],
    dealBreakers: [
      'Irreversible downside risk',
      'Prohibitive ongoing cost',
      'Negative impact on well-being',
      'Unacceptable time commitment',
    ],
  },
}

/**
 * Returns configuration for a specified category and optional subcategory.
 */
export function getCategoryConfig(categoryId, subcategoryId) {
  const normalizedCat = (categoryId || 'electronics').toLowerCase().trim()
  const baseConfig = CATEGORIES_CONFIG[normalizedCat] || CATEGORIES_CONFIG.other || CATEGORIES_CONFIG.electronics

  if (baseConfig.subcategories && baseConfig.subcategories.length > 0) {
    const normalizedSub = (subcategoryId || '').toLowerCase().trim()
    const matchedSub = baseConfig.subcategories.find((s) => s.id === normalizedSub)
      || baseConfig.subcategories[0]

    return {
      ...baseConfig,
      ...matchedSub,
      currentSubcategory: matchedSub.id,
      subcategories: baseConfig.subcategories,
    }
  }

  return baseConfig
}

/**
 * Returns default priority weight object (20% each) for a category and subcategory's factors.
 */
export function getDefaultPrioritiesForCategory(categoryId, subcategoryId) {
  const config = getCategoryConfig(categoryId, subcategoryId)
  const priorities = {}
  config.factors.forEach((f) => {
    priorities[f.key] = 20
  })
  return priorities
}

/**
 * Exported ordered list for category selectors.
 */
export const CATEGORY_LIST = Object.values(CATEGORIES_CONFIG).map((c) => ({
  id: c.id,
  label: c.label,
  icon: c.icon,
  description: c.description,
}))
