"""
Specialized Candidate Evaluation Agents Package.
"""

from .electronics_agents import (
    PerformanceAgent,
    BatteryAgent,
    DisplayAgent,
    BuildAgent,
    UpgradeabilityAgent,
    ValueAgent,
    CameraAgent,
    SoftwareAgent,
    HealthFitnessAgent,
    SmartFeaturesAgent,
    ComfortAgent,
    DurabilityAgent,
    CompatibilityAgent,
    PortabilityAgent,
    ProductivityAgent,
    SoundQualityAgent,
    NoiseCancellationAgent,
    ConnectivityAgent,
)
from .finance_agents import (
    ReturnPotentialAgent,
    RiskAgent,
    LiquidityAgent,
    StabilityAgent,
    GrowthAgent,
    InterestRateAgent,
    EMIAgent,
    TotalCostAgent,
    TenureAgent,
    FlexibilityAgent,
    EligibilityAgent,
    RewardsAgent,
    AnnualFeeAgent,
    BenefitsAgent,
    InterestChargesAgent,
    AcceptanceAgent,
    CoverageAgent,
    PremiumAgent,
    ClaimSupportAgent,
    ExclusionsAgent,
    ReliabilityAgent,
    LongTermValueAgent,
)
from .career_agents import (
    SalaryAgent,
    SkillFitAgent,
    CareerGrowthAgent,
    WorkLifeBalanceAgent,
    CareerStabilityAgent,
    LocationAgent,
    LearningAgent,
)
from .vehicle_agents import (
    VehicleSafetyAgent,
    VehicleMileageAgent,
    VehicleComfortAgent,
    VehicleSpaceAgent,
    VehiclePerformanceAgent,
    VehicleMaintenanceAgent,
    VehicleValueAgent,
)
from .generic_agents import GenericFactorAgent

__all__ = [
    # Electronics
    "PerformanceAgent",
    "BatteryAgent",
    "DisplayAgent",
    "BuildAgent",
    "UpgradeabilityAgent",
    "ValueAgent",
    "CameraAgent",
    "SoftwareAgent",
    "HealthFitnessAgent",
    "SmartFeaturesAgent",
    "ComfortAgent",
    "DurabilityAgent",
    "CompatibilityAgent",
    "PortabilityAgent",
    "ProductivityAgent",
    "SoundQualityAgent",
    "NoiseCancellationAgent",
    "ConnectivityAgent",
    # Vehicle
    "VehicleSafetyAgent",
    "VehicleMileageAgent",
    "VehicleComfortAgent",
    "VehicleSpaceAgent",
    "VehiclePerformanceAgent",
    "VehicleMaintenanceAgent",
    "VehicleValueAgent",
    # Finance
    "ReturnPotentialAgent",
    "RiskAgent",
    "LiquidityAgent",
    "StabilityAgent",
    "GrowthAgent",
    "InterestRateAgent",
    "EMIAgent",
    "TotalCostAgent",
    "TenureAgent",
    "FlexibilityAgent",
    "EligibilityAgent",
    "RewardsAgent",
    "AnnualFeeAgent",
    "BenefitsAgent",
    "InterestChargesAgent",
    "AcceptanceAgent",
    "CoverageAgent",
    "PremiumAgent",
    "ClaimSupportAgent",
    "ExclusionsAgent",
    "ReliabilityAgent",
    "LongTermValueAgent",
    # Career
    "SalaryAgent",
    "SkillFitAgent",
    "CareerGrowthAgent",
    "WorkLifeBalanceAgent",
    "CareerStabilityAgent",
    "LocationAgent",
    "LearningAgent",
    # Generic
    "GenericFactorAgent",
]
